title: Burt.K
email: skyfe79@gmail.com
description: 으라차차 행복한 개발자!
show_downloads: false
google_analytics:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skyfe79
github_username:  skyfe79
about_url: "http://www.daum.net"
archive_url: "http://www.google.com"

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

