title: Burt.K
email: skyfe79@gmail.com
description: 코코아를 좋아하는 프로그래머입니다 ;)
show_downloads: false
google_analytics:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skyfe79
github_username:  skyfe79
about_url: "/about"
archive_url: "/archive"
opensources_url: "/opensources"
books_url: "/books"

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
pygments_options:
  tabsize: 4
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

