title: Burt.K
email: skyfe79@gmail.com
description: Modernist is a theme for GitHub Pages.
show_downloads: true
google_analytics: false
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skyfe79
github_username:  skyfe79

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  #- jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

